export const liveMatch = [
  {
    id: "1234",
    leagueName: "LaLiga",
    leagueIcon: require("./assets/images/laliga.png"),
    matchType: "LIVE",
    stadiumName: "Camp Nou",
    homeTeam: "FC Barcelona",
    homeTeamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
    homeTeamScore: 1,
    awayTeam: "Real Madrid CF",
    awayTeamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
    awayTeamScore: 1,
    matchDetails: [
      {
        title: "Shots",
        type: "number",
        home: 5,
        away: 8,
      },
      {
        title: "Shots on target",
        type: "number",
        home: 2,
        away: 4,
      },
      {
        title: "Possession",
        type: "percent",
        home: 55,
        away: 45,
      },
      {
        title: "Passes",
        type: "number",
        home: 65,
        away: 120,
      },
      {
        title: "Pass accuracy",
        type: "percent",
        home: 59,
        away: 41,
      },
      {
        title: "Fouls",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Offsides",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Cross",
        type: "number",
        home: 10,
        away: 23,
      },
      {
        title: "Corners",
        type: "number",
        home: 3,
        away: 6,
      },
      {
        title: "Goalkeeper Saves",
        type: "number",
        home: 7,
        away: 8,
      },
    ],
    timeLine: [
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Dani Alves",
        playerImage: require("./assets/images/daniAlves.png"),
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "35",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Karim Benzema",
        playerImage: require("./assets/images/benzema.png"),
        assistName: "Vini Jr",
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "49",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Casemiro",
        playerImage: require("./assets/images/casemiro.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "52",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Luuk de Jong",
        playerImage: require("./assets/images/dejong.png"),
        assistName: "Ousmane Dembele",
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "69",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "E. MILITÃO",
        playerImage: require("./assets/images/daniel.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "70",
      },
    ],
    matchNo: 15,
    timePlayed: 25,
  },
  {
    id: "3425",
    leagueName: "LaLiga",
    leagueIcon: require("./assets/images/laliga.png"),
    matchType: "LIVE",
    stadiumName: "Camp Nou",
    homeTeam: "FC Barcelona",
    homeTeamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
    homeTeamScore: 1,
    awayTeam: "Real Madrid CF",
    awayTeamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
    awayTeamScore: 1,
    matchDetails: [
      {
        title: "Shots",
        type: "number",
        home: 5,
        away: 8,
      },
      {
        title: "Shots on target",
        type: "number",
        home: 2,
        away: 4,
      },
      {
        title: "Possession",
        type: "percent",
        home: 55,
        away: 45,
      },
      {
        title: "Passes",
        type: "number",
        home: 65,
        away: 120,
      },
      {
        title: "Pass accuracy",
        type: "percent",
        home: 59,
        away: 41,
      },
      {
        title: "Fouls",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Offsides",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Cross",
        type: "number",
        home: 10,
        away: 23,
      },
      {
        title: "Corners",
        type: "number",
        home: 3,
        away: 6,
      },
      {
        title: "Goalkeeper Saves",
        type: "number",
        home: 7,
        away: 8,
      },
    ],
    timeLine: [
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Dani Alves",
        playerImage: require("./assets/images/daniAlves.png"),
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "35",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Karim Benzema",
        playerImage: require("./assets/images/benzema.png"),
        assistName: "Vini Jr",
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "49",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Casemiro",
        playerImage: require("./assets/images/casemiro.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "52",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Luuk de Jong",
        playerImage: require("./assets/images/dejong.png"),
        assistName: "Ousmane Dembele",
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "69",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "E. MILITÃO",
        playerImage: require("./assets/images/daniel.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "70",
      },
    ],
    matchNo: 16,
    timePlayed: 25,
  },
  {
    id: "3214",
    leagueName: "LaLiga",
    leagueIcon: require("./assets/images/laliga.png"),
    matchType: "LIVE",
    stadiumName: "Camp Nou",
    homeTeam: "FC Barcelona",
    homeTeamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
    homeTeamScore: 1,
    awayTeam: "Real Madrid CF",
    awayTeamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
    awayTeamScore: 1,
    matchDetails: [
      {
        title: "Shots",
        type: "number",
        home: 5,
        away: 8,
      },
      {
        title: "Shots on target",
        type: "number",
        home: 2,
        away: 4,
      },
      {
        title: "Possession",
        type: "percent",
        home: 55,
        away: 45,
      },
      {
        title: "Passes",
        type: "number",
        home: 65,
        away: 120,
      },
      {
        title: "Pass accuracy",
        type: "percent",
        home: 59,
        away: 41,
      },
      {
        title: "Fouls",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Offsides",
        type: "number",
        home: 10,
        away: 8,
      },
      {
        title: "Cross",
        type: "number",
        home: 10,
        away: 23,
      },
      {
        title: "Corners",
        type: "number",
        home: 3,
        away: 6,
      },
      {
        title: "Goalkeeper Saves",
        type: "number",
        home: 7,
        away: 8,
      },
    ],
    timeLine: [
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Dani Alves",
        playerImage: require("./assets/images/daniAlves.png"),
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "35",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Karim Benzema",
        playerImage: require("./assets/images/benzema.png"),
        assistName: "Vini Jr",
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "49",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "Casemiro",
        playerImage: require("./assets/images/casemiro.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "52",
      },
      {
        type: "Goal!!!",
        typeImage: require("./assets/images/footBall.png"),
        playerName: "Luuk de Jong",
        playerImage: require("./assets/images/dejong.png"),
        assistName: "Ousmane Dembele",
        teamName: "FC Barcelona",
        teamColor: "#008AD8",
        teamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
        time: "69",
      },
      {
        type: "Yellow Card",
        typeImage: require("./assets/images/yellowCard.png"),
        playerName: "E. MILITÃO",
        playerImage: require("./assets/images/daniel.png"),
        teamName: "Real Madrid CF",
        teamColor: "white",
        teamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
        time: "70",
      },
    ],
    matchNo: 17,
    timePlayed: 25,
  },
];

export const upcomingMatch = [
  {
    id: "1324",
    leagueName: "Premier League",
    leagueIcon: require("./assets/images/premier.png"),
    homeTeam: "Manchester City",
    homeTeamIcon: require("./assets/images/teamsLogo/manchesterCity.png"),
    awayTeam: "Arsenal FC",
    awayTeamIcon: require("./assets/images/teamsLogo/arsenal.png"),
    timeReamin: "13h 24min",
  },
  {
    id: "1758",
    leagueName: "Champions League",
    leagueIcon: require("./assets/images/champions.png"),
    homeTeam: "Aston Villa",
    homeTeamIcon: require("./assets/images/teamsLogo/aston.png"),
    awayTeam: "Real Madrid CF",
    awayTeamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
    timeReamin: "13h 24min",
  },
  {
    id: "13567",
    leagueName: "Premier League",
    leagueIcon: require("./assets/images/premier.png"),
    homeTeam: "FC Barcelona",
    homeTeamIcon: require("./assets/images/teamsLogo/fcBarcelona.png"),
    awayTeam: "Arsenal FC",
    awayTeamIcon: require("./assets/images/teamsLogo/arsenal.png"),
    timeReamin: "13h 24min",
  },
  {
    id: "2314",
    leagueName: "Champions League",
    leagueIcon: require("./assets/images/champions.png"),
    homeTeam: "Real Madrid",
    homeTeamIcon: require("./assets/images/teamsLogo/realMadrid.png"),
    awayTeam: "Manchester City",
    awayTeamIcon: require("./assets/images/teamsLogo/manchesterCity.png"),
    timeReamin: "13h 24min",
  },
];

export const topPlayers = [
  {
    id: "123",
    playerFName: "Lionel",
    playerLName: "Messi",
    leagueName: "League 1",
    playerImage: require("./assets/images/messi.png"),
    leagueIcon: require("./assets/images/league.png"),
    clubName: "Paris Saint-Germein",
    clubRating: 6.95,
    clubIcon: require("./assets/images/teamsLogo/psg.png"),
    countryIcon: require("./assets/images/teamsLogo/argentina.png"),
    gamesPlayed: 34,
    scoreGoals: 14,
    position: "FORWARD",
    nextGames: [
      {
        teamName: "RC Strasbourg",
        teamIcon: require("./assets/images/teamsLogo/strasbourg.png"),
        avgRating: 5.45,
        date: "2/10/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/15/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/20/2023",
      },
    ],
  },
  {
    id: "231",
    playerFName: "Cristiano",
    playerLName: "Ronaldo",
    playerImage: require("./assets/images/ronaldo.png"),
    leagueName: "English Premier league",
    leagueIcon: require("./assets/images/barclays.png"),
    clubName: "Manchester United",
    clubRating: 6.9,
    clubIcon: require("./assets/images/teamsLogo/manU.png"),
    countryIcon: require("./assets/images/teamsLogo/portugal.png"),
    gamesPlayed: 30,
    scoreGoals: 12,
    position: "FORWARD",
    nextGames: [
      {
        teamName: "RC Strasbourg",
        teamIcon: require("./assets/images/teamsLogo/strasbourg.png"),
        avgRating: 5.45,
        date: "2/10/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/15/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/20/2023",
      },
    ],
  },
  {
    id: "321",
    playerFName: "Lionel",
    playerLName: "Messi",
    playerImage: require("./assets/images/messi.png"),
    leagueName: "League 1",
    leagueIcon: require("./assets/images/league.png"),
    clubName: "Paris Saint-Germein",
    clubRating: 6.9,
    clubIcon: require("./assets/images/teamsLogo/psg.png"),
    countryIcon: require("./assets/images/teamsLogo/argentina.png"),
    gamesPlayed: 34,
    scoreGoals: 14,
    position: "FORWARD",
    nextGames: [
      {
        teamName: "RC Strasbourg",
        teamIcon: require("./assets/images/teamsLogo/strasbourg.png"),
        avgRating: 5.45,
        date: "2/10/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/15/2023",
      },
      {
        teamName: "RC Strasbourg",
        teamIcon: "",
        avgRating: 5.45,
        date: "2/20/2023",
      },
    ],
  },
];

export const Standing = [
  {
    teamName: "FC Barcelona",
    teamShortName: "FCB",
    teamLogo: require("./assets/images/miniLogo/barca.png"),
    matchPlayed: 12,
    matchWin: 8,
    matchDraw: 3,
    matchLost: 1,
    points: 27,
  },
  {
    teamName: "Atlético de Madrid",
    teamShortName: "ATM",
    teamLogo: require("./assets/images/miniLogo/athletico.png"),
    matchPlayed: 12,
    matchWin: 7,
    matchDraw: 4,
    matchLost: 1,
    points: 25,
  },
  {
    teamName: "Sevilla FC",
    teamShortName: "SEV",
    teamLogo: require("./assets/images/miniLogo/sevilla.png"),
    matchPlayed: 12,
    matchWin: 7,
    matchDraw: 3,
    matchLost: 2,
    points: 24,
  },
  {
    teamName: "Real Betis",
    teamShortName: "RBT",
    teamLogo: require("./assets/images/miniLogo/betis.png"),
    matchPlayed: 12,
    matchWin: 6,
    matchDraw: 2,
    matchLost: 4,
    points: 20,
  },
  {
    teamName: "Athletic Club",
    teamShortName: "ATB",
    teamLogo: require("./assets/images/miniLogo/athletic.png"),
    matchPlayed: 11,
    matchWin: 5,
    matchDraw: 3,
    matchLost: 3,
    points: 18,
  },
  {
    teamName: "Villarreal CF",
    teamShortName: "VCF",
    teamLogo: require("./assets/images/miniLogo/villareal.png"),
    matchPlayed: 10,
    matchWin: 4,
    matchDraw: 1,
    matchLost: 5,
    points: 16,
  },
  {
    teamName: "Real Madrid CF",
    teamShortName: "RMA",
    teamLogo: require("./assets/images/miniLogo/real.png"),
    matchPlayed: 13,
    matchWin: 8,
    matchDraw: 4,
    matchLost: 1,
    points: 28,
  },
];

